Icon:
  description: "The icon that you wish to use"
  type: string
  default: 'map-marker-alt'

svg_icons: 
  description: "To prepare an alternate icon, add it to this list"
  default: 'map'
  type: 'list'
  list_type: 'compact'
